//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFCRUD.pcrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clx
    {
        public int Std_id { get; set; }
        public string Std_name { get; set; }
        public int Age { get; set; }
        public int Fee { get; set; }
        public string City { get; set; }
        public double Percentage { get; set; }
    }
}
